Adding `period_prior_to_index` function
JuliaHealth/OMOPCDMPathways pull request #35
Opened 2024-06-05 18:03 UTC by Jay-sanjay

**This PR is related to #1**

## PR CheckList

- [x] Added the very first dispatch for `period_prior_to_index` function
- [x] Added the test-suite for the same
- [ ]  Added the Doc-strings

2024-06-24 04:26 UTC, TheCedarPrince requested changes
Hey @Jay-sanjay ,

This looks pretty good -- left some comments with the biggest suggested changes being in the second dispatch. Additionally, could you add an issue so we don't forget about it to later come back and add a dispatch for when you pass in just person IDs instead of cohort IDs? I am fine with us focusing on Cohort IDs first, but later, handling person IDs generally would be great too.

Great work so far Jay!

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +
Could you remove this now?

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +function Period_prior_to_index(cohort_id::Vector, conn; date_prior=Day(100), tab=cohort)
Could you make this lowercase? i.e. `period_prior_to_index` ?

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +Given a vector of cohort IDs, this function returna a DataFrame with the cohort_start_date adjusted by the date_prior.
Could we rephrase this to the following:

"Given `cohort_id`'s, return a `DataFrame` with the `cohort_start_date` adjusted to prior each subjects' cohort entry date (i.e. their `cohort_start_date`).

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +- `date_prior` - period prior to the index date; default is 100 days
Could we update this as:

`date_prior::Dates.AbstractTime` - how much time prior the index date should be adjusted by; accepts a `Dates.AbstractTime` object such as `Day`, `Month`, etc. (Default: `Day(100)`)

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +- `tab` - the `SQLTable` representing the cohort table; default `cohort`
Small tweak but could you say:

- `tab` - the `SQLTable` representing the cohort table. (Default: `cohort`)

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +- DataFrame with the cohort_start_date adjusted by the date_prior.
Small tweak:

`cohort_start_date` adjusted by the `date_prior`

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +    # TODO: Is it really necessary to add this check ??
We concluded this would be a nice check to see if the dataframe is not empty. So you can get rid of this comment.

2024-06-24 04:26 UTC, TheCedarPrince commented on test/Data-Preprocessing/preprocessing.jl
> +    println(result)
Could you get rid of this line? And do you still need the dummy test or can they be removed?

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +- `date_prior` - period prior to the index date; default is 100 days
Since this method only accepts a function that modifies the `cohort_start_date` per person, this argument and its usage should be deleted.

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +- `start_date_on_person` - function that returns the SQL query to get the start date of the person
I would suggest changing this name to `index_date_func` and in the docstring specifies that the function should accept three arguments being `df` (the dataframe computed for the cohorts),  `tables`, and `conn` with a note that it should return a DataFrame and not SQL. I think the function a user passes in should allow for execution of SQL and additional post-processing if they need it.

P.S. This will be cool as that means it could accept TidierDB queries someday down the road too.

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +    df = DBInterface.execute(conn, String(sql)) |> DataFrame
You'll need to put this line before sql to compute the cohorts.

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +        person_ids::Vector,
Shouldn't this be cohorts?

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +    # TODO: Is it really necessary to add this check ??
I think this section should be removed since you no longer have `date_prior`

2024-06-24 04:26 UTC, TheCedarPrince commented on test/Data-Preprocessing/preprocessing.jl
> +    println(first(df, 5))
Should these tests be cleaned up here?

2024-06-24 04:26 UTC, TheCedarPrince commented on test/Data-Preprocessing/preprocessing.jl
> +    @test test_subject_ids == result.subject_id[1:5]
Can you make sure to clean the tests here? They seem fine but there might be a few extraneous prints here and there.

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +"""
Could you add an example section here about how to call this function?

2024-06-24 04:26 UTC, TheCedarPrince commented on src/preprocessing.jl
> +"""
Could you add an example section here about how to call this function and how to pass in a function into the argument which accepts a user defined function? So show how to make a function? Thanks!

2024-06-24 04:54 UTC, Jay-sanjay commented on src/preprocessing.jl
> +
Sure !

2024-06-24 04:55 UTC, Jay-sanjay commented on test/Data-Preprocessing/preprocessing.jl
> +    println(first(df, 5))
Yes they can be removed now

2024-06-24 05:59 UTC, Jay-sanjay commented on src/preprocessing.jl
> +- `start_date_on_person` - function that returns the SQL query to get the start date of the person
but, then where do we adjust the dates based on `date-prior` ?

2024-06-26 18:28 UTC, TheCedarPrince commented on src/preprocessing.jl
> +- `start_date_on_person` - function that returns the SQL query to get the start date of the person
Oh so I imagine the user manually defines and applies the transformation to the start_date column within the function they pass in. Here's a simplified sketch with pseudo code:

```julia
my_func(df, tables, conn)

for patient in eachrow(df)
# Some criteria to meet
    if Criteria 1
        update patient.start_date by some change
# Some criteria to meet
    elseif Criteria 2

# ... Other additional create and transformations

return df

end
```

So the `date_prior` variable goes away and instead, the user passes in exactly how they want to transform each patient based on some criteria they are looking for in the function they provide. Does that make more sense?

2024-07-17 16:56 UTC, Jay-sanjay commented
@TheCedarPrince  can we ignore the code-coverage for now ?

2024-08-09 16:38 UTC, TheCedarPrince commented
@Jay-sanjay , if you could add one more test that involves checking the result of a defective DataFrame (like an empty dataframe), that would be perfect and get CodeCov back up to 100. Then we could merge this.

2024-08-23 18:28 UTC, TheCedarPrince approved these changes
Looks great to me! Let's merge. GREAT JOB!

2024-08-23 18:28 UTC, merged