Added `EraDuration`  function
JuliaHealth/OMOPCDMPathways pull request #36
Opened 2024-06-05 18:12 UTC by Jay-sanjay

**This PR is related to #2 **

## PR CheckList

- [x] Added the very first dispatch for `EraDuration` function
- [x] Added the test-suite for the same
- [ ]  Added the Doc-strings  
- [ ]  Added the remaining dispatches with test-suite

2024-06-06 22:09 UTC, TheCedarPrince commented
Just a note that the original implementation comes from this line of code: https://github.com/mi-erasmusmc/TreatmentPatterns/blob/171b60af7e76f63e09f2c2d48e2b811ce1dafff0/R/ConstructPathways.R#L195C1-L205C2 -- still doing a review here! :smile:

2024-06-27 05:52 UTC, TheCedarPrince requested changes
Just some small tweaks -- great job Jay!

2024-06-27 05:52 UTC, TheCedarPrince commented on src/preprocessing.jl
> +
Hey Jay, could you add an example here?

2024-06-27 05:52 UTC, TheCedarPrince commented on src/preprocessing.jl
> +Given a treatment history dataframe, this function filters out rows where the difference between drug_exposure_start and drug_exposure_end is less than minEraDuration.
Could you format the docstring to look more like this, Jay: https://github.com/JuliaHealth/OMOPCDMCohortCreator.jl/blob/637960b01f08ec3ce6e66c73d74bddf8556dde2e/src/getters.jl#L420 ? With proper markup and everything?

2024-06-27 05:52 UTC, TheCedarPrince commented on src/preprocessing.jl
> +    @info "After minEraDuration: $(nrow(treatment_history))"  # For debugging purposes
Could you clean up this function and remove debugging?

2024-06-27 05:52 UTC, TheCedarPrince commented on src/preprocessing.jl
> +function EraDuration(treatment_history::DataFrame, minEraDuration)
Could we rename the function to `calculate_era_duration`?

2024-06-28 16:49 UTC, TheCedarPrince approved these changes
LGTM -- Let's merge!

2024-06-28 17:17 UTC, Jay-sanjay commented
@TheCedarPrince  the reason that deployment was failing was that it was not included to the api.md files. Though I have added it it must throw a merge conflict because we have a same thing added in `period_prior_to_index`

2024-06-28 17:37 UTC, TheCedarPrince approved these changes
Ah thanks for the fixes! Let's merge it in! :smile: Go ahead and merge! :D

2024-06-28 17:37 UTC, TheCedarPrince approved these changes
Ah thanks for the fixes! Let's merge it in! :smile: Go ahead and merge! :D

2024-06-28 17:41 UTC, merged