Added the combination-window function
JuliaHealth/OMOPCDMPathways pull request #63
Opened 2024-08-27 13:40 UTC by Jay-sanjay

- [x]  Added the actual function
- [ ]  Added the test suite
- [ ]  Added the doc-strings
- [ ]  Added the example in the doc-strings

2024-08-31 18:55 UTC, TheCedarPrince requested changes
Nice work @Jay-sanjay ! This is one of the trickier parts of the implementation so I added a bunch of clarifying questions as I had a little bit of trouble following your implementations. Additionally, could you add docstrings to your functions here? I think that would be helpful to know what these functions are doing.

Thanks!

2024-08-31 18:55 UTC, TheCedarPrince commented on src/preprocessing.jl
> +function selectRowsCombinationWindow(treatment_history::DataFrame)
Just a note, since the selectRowsCombinationWindow function mutates inplace the treatment_history DataFrame, the function name should be `selectRowsCombinationWindow!` to denote that it is transforming data inplace.

2024-08-31 18:55 UTC, TheCedarPrince commented on src/preprocessing.jl
> +    treatment_history.GAP_PREVIOUS = Dates.value.(treatment_history.event_start_date .- shift(treatment_history.event_end_date, 1))
Could you explain to me carefully what this line is doing? What is shift doing?

2024-08-31 18:55 UTC, TheCedarPrince commented on src/preprocessing.jl
> +        selected_rows = findall(treatment_history.SELECTED_ROWS .== 1)
Could you explain to me exactly what these lines are doing? Could you give me as much details as possible and how this relates to the original implementation?

2024-08-31 18:55 UTC, TheCedarPrince commented on src/preprocessing.jl
> +                treatment_history[i-1, :event_end_date] = treatment_history[i, :event_start_date]
This looks about right to me.

2024-08-31 18:55 UTC, TheCedarPrince commented on src/preprocessing.jl
> +                    append!(treatment_history, DataFrame(new_row'))
This prototype implementation looks good and seems like it simplified the R code. Cool stuff!

2024-08-31 18:55 UTC, TheCedarPrince commented on src/preprocessing.jl
> +                    treatment_history[i, :event_end_date] = treatment_history[i-1, :event_end_date]
I am not entirely sure this is right looking at the Reference R Code here: https://github.com/mi-erasmusmc/TreatmentPatterns/blob/171b60af7e76f63e09f2c2d48e2b811ce1dafff0/R/ConstructPathways.R#L350

Did you just dramatically simplify the implementation here? Or what did you do? I am having a little difficulty following your implementation versus the R version.

2024-09-09 05:04 UTC, Jay-sanjay commented on src/preprocessing.jl
> +function selectRowsCombinationWindow(treatment_history::DataFrame)
Thanks ! I actually missed that convention.

2024-09-15 17:33 UTC, Jay-sanjay commented on src/preprocessing.jl
> +    treatment_history.GAP_PREVIOUS = Dates.value.(treatment_history.event_start_date .- shift(treatment_history.event_end_date, 1))
I initially made the  shift function to shift the values of the array up-down by specified number of rows, but in my new revised implementation we no longer need it...

2024-10-22 01:20 UTC, TheCedarPrince approved these changes
Hey @Jay-sanjay , I fixed things up here and this looks good to me to merge. Go for it!

2024-10-24 10:49 UTC, merged